# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.1"

package:
  name: wire-file
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wire-file/wire_file-${{ version }}.tar.gz
    sha256: 66c2aee88e7ee50dc6fddd17ab925c3d4d8811d675a30053dcb5cfc7e44e9ab5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - wiredb >=0.4.0,<0.5.0

tests:
  - python:
      imports: wire_file
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/wiredb
  summary: Wire for storing to a file.

extra:
  recipe-maintainers:
    - davidbrochart
