# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.0"

package:
  name: wire-file
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wire-file/wire_file-${{ version }}.tar.gz
    sha256: 099bac80d581fbd99962d1a80cef771dc9d09e0c10e5fd0042b30df303c10fff

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - wiredb >=0.7.0,<0.8.0

tests:
  - python:
      imports: wire_file
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/wiredb
  summary: Wire for storing to a file.

extra:
  recipe-maintainers:
    - davidbrochart
